language: minimal

before_script:
  - docker pull mcr.microsoft.com/powershell:latest

script:
  - "docker run --rm -it -v ./:/src -e NUGET_APIKEY=$NUGET_APIKEY mcr.microsoft.com/powershell:latest Publish-Module -Path /src/ -NuGetApiKey $env:NUGET_APIKEY"