[package]
name = "git-tool"
version = "0.1.0"
authors = ["Benjamin Pannell <benjamin@pannell.dev>"]
edition = "2018"

# See more keys and their definitions at https://doc.rust-lang.org/cargo/reference/manifest.html

[dependencies]
clap = { version = "2.33.0", features = ["yaml"] }
serde = { version = "1.0", features = ["derive", "rc"] }
serde_yaml = "0.8"
gtmpl = "0.5.7"
hyper = "0.13"
hyper-tls = "0.4.1"
http = "0.2.1"
tokio = { version = "0.2", features = ["full"] }
async-trait = "0.1.30"
glob = "0.3.0"
chrono = "0.4"