[package]
name = "git-tool"
version = "0.2.0"
authors = ["Benjamin Pannell <benjamin@pannell.dev>"]
edition = "2018"

# See more keys and their definitions at https://doc.rust-lang.org/cargo/reference/manifest.html

[dependencies]
async-trait = "0.1"
base64 = "0.12"
chrono = "0.4"
clap = { version = "2.33", features = ["yaml"] }
gtmpl = "0.5"
http = "0.2"
hyper = "0.13"
yup-hyper-mock = "4.0"
hyper-tls = "0.4"
itertools = "0.9"
keyring = "0.9"
log = "0.4"
rpassword = "4.0"
semver = "0.10"
sentry = { version = "0.19", features = ["log", "test"] }
serde = { version = "1.0", features = ["derive", "rc"] }
serde_json = "1.0"
serde_yaml = "0.8"
shell-words = "1.0"
tempfile = "3.1"
tokio = { version = "0.2", features = ["full"] }

[profile.release]
debug = true