pool:
  name: Hosted Ubuntu 1604

variables:
    "Go.Version": "1.12.6"

steps:
- task: gittools.gitversion.gitversion-task.GitVersion@4
  displayName: GitVersion
  inputs:
    preferBundledVersion: false

- task: GoTool@0
  displayName: 'Use Go $(Go.Version)'
  inputs:
    version: "$(Go.Version)"

- task: Go@0
  displayName: 'go test'
  inputs:
    command: test
    arguments: '-v -race ./...'

- task: PowerShell@2
  displayName: 'Build Variants'
  inputs:
    targetType: filePath
    filePath: './ci/build-all.ps1'
    arguments: '-Version $(GitVersion.FullSemVer)'

- task: CopyFiles@2
  displayName: 'Staging Directory copy'
  inputs:
    SourceFolder: bin
    Contents: '*/git-tool-*'
    TargetFolder: '$(Build.ArtifactStagingDirectory)'

- task: PublishBuildArtifacts@1
  displayName: 'Publish Artifact: drop/Git-Tool'
  inputs:
    ArtifactName: 'drop/Git-Tool'
