pool:
  name: Hosted Ubuntu 1604

variables:
    "Go.Version": "1.12.6"

steps:
- task: UseDotNet@2
  displayName: 'Use .NET Core runtime 2.2.4'
  inputs:
    packageType: runtime
    version: 2.2.4
    
- task: DownloadGitHubRelease@0
  displayName: 'Download GitHub Release'
  inputs:
    connection: GitHub
    userRepository: GitTools/GitVersion
    itemPattern: 'GitVersion-bin-coreclr*.zip'
    downloadPath: tmp/

- task: ExtractFiles@1
  displayName: 'Extract files '
  inputs:
    archiveFilePatterns: 'tmp/*.zip'
    destinationFolder: 'tmp/'
    cleanDestinationFolder: false

- task: DotNetCoreCLI@2
  displayName: 'dotnet GitVersion.dll'
  inputs:
    command: custom
    custom: 'tmp/GitVersion.dll'
    arguments: '/output buildserver'

- task: GoTool@0
  displayName: 'Use Go $(Go.Version)'
  inputs:
    version: "$(Go.Version)"

- task: Go@0
  displayName: 'go test'
  inputs:
    command: test
    arguments: '-v -race ./...'

- task: PowerShell@2
  displayName: 'Build Variants'
  inputs:
    targetType: filePath
    filePath: './ci/build-all.ps1'
    arguments: '-Version $(GitVersion.FullSemVer)'

- task: CopyFiles@2
  displayName: 'Staging Directory copy'
  inputs:
    SourceFolder: bin
    Contents: 'git-tool-*'
    TargetFolder: '$(Build.ArtifactStagingDirectory)'

- task: PublishBuildArtifacts@1
  displayName: 'Publish Artifact: drop/Git-Tool'
  inputs:
    ArtifactName: 'drop/Git-Tool'
