name: Build Release
on:
  push:
    tags:
      - 'v*'
    paths:
      - '*.go'
      - '!*_test.go'
jobs:
    
  build:
    name: Build
    runs-on: ubuntu-latest
    strategy:
      matrix:
        os: [windows, linux, freebsd, darwin]
        arch: [amd64, "386"]
        include:
          - os: windows
            extension: ".exe"
    
    steps:
    - name: Set up Go 1.13
      uses: actions/setup-go@v1
      with:
        go-version: 1.13
      id: go

    - name: Check out code into the Go module directory
      uses: actions/checkout@v1
      
    - name: Fetch tags
      run: |
        git fetch --tags

    - name: Build
      run: go build -o bin/git-tool-${{ matrix.os }}-${{ matrix.arch }}${{ matrix.extension }} -ldflags "-X main.version=$(git describe --tags --always)" ./cmd/git-tool/main.go
      shell: pwsh
      env:
        GOOS: ${{ matrix.os }}
        GOARCH: ${{ matrix.arch }}

    - name: Upload artifacts
      uses: actions/upload-artifact@v1
      with:
        name: "binaries"
        path: bin/git-tool-${{ matrix.os }}-${{ matrix.arch }}${{ matrix.extension }}
