name: Test Changes
on: [push]
jobs:
  test:
    name: Test
    runs-on: ubuntu-latest
    steps:
    - name: Get Rust Nightly
      uses: actions-rs/toolchain@v1
      with:
        toolchain: nightly
        override: true

    - name: Check out code
      uses: actions/checkout@v1
        
    - name: Run tests
      uses: actions-rs/cargo@v1.0.1
      with:
        command: test
        args: --all-features --no-fail-fast
      env:
        CARGO_INCREMENTAL: '0'
        RUSTFLAGS: '-Zprofile -Ccodegen-units=1 -Copt-level=0 -Clink-dead-code -Coverflow-checks=off'
        
    - name: Collect code coverage
      uses: actions-rs/tarpaulin@v0.1.0
      with:
        args: --out Lcov
    
    - name: Upload code coverage
      uses: codecov/codecov-action@v1.0.5
      with:
        token: ${{ secrets.CODECOV_TOKEN }}
        file: ./lcov.info
