name: Test Changes
on: [push]
jobs:
  test:
    name: Test
    runs-on: ubuntu-latest
    steps:
    - name: Install Dependencies
      run: |
        sudo apt-get update
        sudo apt-get install libdbus-1-3 libdbus-1-dev
      
    - name: Get Rust Nightly
      uses: actions-rs/toolchain@v1
      with:
        toolchain: nightly
        override: true

    - name: Check out code
      uses: actions/checkout@v1

    # - uses: actions/cache@v2
    #   with:
    #     path: |
    #       ~/.cargo/registry
    #       ~/.cargo/git
    #       target
    #       !target/*/**.gcda
    #     key: ${{ runner.os }}-cargo-${{ hashFiles('**/Cargo.lock') }}-v2

    - name: Prepare Git for Tests
      run: |
        git config --global user.name "Test User"
        git config --global user.email "test@example.com"
        
    - name: Run tests
      uses: actions-rs/cargo@v1.0.3
      with:
        command: test
        args: --all-features --no-fail-fast
      env:
        CARGO_INCREMENTAL: '0'
        RUSTFLAGS: '-Zprofile -Ccodegen-units=1 -Copt-level=0 -Clink-dead-code -Coverflow-checks=off'
        
    - name: Collect code coverage
      id: coverage
      uses: actions-rs/grcov@v0.1.6
    
    - name: Upload code coverage
      uses: codecov/codecov-action@v1.0.10
      with:
        token: ${{ secrets.CODECOV_TOKEN }}
        file: ./lcov.info
